### ISSUE TITLE
Wiki Results should be updated (false positives that have been solved in the meantime)

### ISSUE THREAD

**Issue by theemstra** [wpengine/phpcompat#103]
The results page https://github.com/wpengine/phpcompat/wiki/Results is outdated, since there are patches supplied and merged already for known issues like for WooCommerce (#119) and Jetpack (#68)

**Comment by jrfnl** [comment]
Related #82

**Comment by octalmage** [comment]
Closing in favor of #82. The page is a wiki, feel free to update it!
