### ISSUE TITLE
Still FALSE POSITIVE: Using break outside of a loop

### ISSUE THREAD

**Issue by octalmage** [wpengine/phpcompat#110]
Still FALSE POSITIVE: Using &lsquo;break&rsquo; outside of a loop<br>
http://ift.tt/2jZNKTb<br><p>Replies: 0</p>
<p>Here&rsquo;s another false report:</p>
<p>/wp-content/plugins/shortcodes-ultimate/inc/core/tools.php<br>
681 | ERROR | Using &lsquo;break&rsquo; outside of a loop or switch structure is invalid and will throw a fatal error since PHP 7.0<br>
&mdash;<br>
foreach ( array( &lsquo;media&rsquo;, &lsquo;posts&rsquo;, &lsquo;category&rsquo;, &lsquo;taxonomy&rsquo; ) as $type )<br>
if ( strpos( trim( $args[&lsquo;source&rsquo;] ), $type . &lsquo;:&rsquo; ) === 0 ) {<br>
$args[&lsquo;source&rsquo;] = array(&lsquo;type&rsquo; =&gt; $type,&rsquo;val&rsquo; =&gt; (string) trim( str_replace( array( $type . &lsquo;:&rsquo;, &lsquo; &lsquo; ), &rdquo;, $args[&lsquo;source&rsquo;] ), &lsquo;,&rsquo; ) );<br>
break;<br>
}</p>
<br><br>
via WordPress.org Forums &raquo; All Topics http://ift.tt/2gps7Vy<br>
February 07, 2017 at 02:16PM

**Comment by jrfnl** [comment]
Related: https://github.com/wimg/PHPCompatibility/issues/292

**Comment by pcfreak30** [comment]
Happening on https://github.com/dompdf/dompdf/blob/0.6.2-hotfix/include/table_frame_decorator.cls.php too.

`181 | ERROR | Using 'break' outside of a loop or switch structure is invalid and will throw a fatal error since PHP 7.0`
