### ISSUE TITLE
Problem with new version (502  no loading bar)

### ISSUE THREAD

**Issue by octalmage** [wpengine/phpcompat#113]
Problem with new version (502 + no loading bar)<br>
http://ift.tt/2mmiLgS<br><p>Replies: 0</p>
<p>Hi,</p>
<p>I updated the plugin (hoping that it would show less false positives) and I now get the following error:</p>
<p>Error: Bad Gateway<br>
Status: 502</p>
<p>Also, I no longer see a loading bar. Is this normal?</p>
<p>Can&rsquo;t seem to be able to stop a scan once it started, and the little &ldquo;thinking wheel&rdquo; at the right keep spinning forever.</p>
<p>Any help would be most welcome. Thanks!</p>
<br><br>
via WordPress.org Forums &raquo; [PHP Compatibility Checker] Support http://ift.tt/2gps7Vy<br>
February 22, 2017 at 01:23PM

**Comment by hello-jason** [comment]
Related wordpress.org topic, for clarity: https://wordpress.org/support/topic/problem-with-new-version-502-no-loading-bar/#post-8840609
