### ISSUE TITLE
FALSE POSITIVE: Showing CloudFlare as not PHP 7 Compatible

### ISSUE THREAD

**Issue by octalmage** [wpengine/phpcompat#116]
FALSE POSITIVE: Showing CloudFlare as not PHP 7 Compatible<br>
http://ift.tt/2lihCFZ<br><p>Replies: 0</p>
<p>Ran some tests on a few more fairly common plugins, and found that the CloudFlare plugin is getting a false positive.</p>
<p>Here&rsquo;s the clip from the report:</p>
<pre>
<code>
FILE: /XXXXXX/wp-content/plugins/cloudflare/vendor/guzzle/guzzle/src/Guzzle/Service/Resource/AbstractResourceIteratorFactory.php
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
 3 | ERROR | 'resource' is a reserved keyword as of PHP version 7.0 and cannot be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------

FILE: /XXXXXX/wp-content/plugins/cloudflare/vendor/guzzle/guzzle/src/Guzzle/Service/Resource/Model.php
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
 3 | ERROR | 'resource' is a reserved keyword as of PHP version 7.0 and cannot be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------

FILE: /XXXXXX/wp-content/plugins/cloudflare/vendor/guzzle/guzzle/src/Guzzle/Service/Resource/ResourceIteratorClassFactory.php
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
 3 | ERROR | 'resource' is a reserved keyword as of PHP version 7.0 and cannot be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------

FILE: /XXXXXX/wp-content/plugins/cloudflare/vendor/guzzle/guzzle/src/Guzzle/Service/Resource/ResourceIteratorApplyBatched.php
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
 3 | ERROR | 'resource' is a reserved keyword as of PHP version 7.0 and cannot be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------

FILE: /XXXXXX/wp-content/plugins/cloudflare/vendor/guzzle/guzzle/src/Guzzle/Service/Resource/CompositeResourceIteratorFactory.php
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
 3 | ERROR | 'resource' is a reserved keyword as of PHP version 7.0 and cannot be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------

FILE: /XXXXXX/wp-content/plugins/cloudflare/vendor/guzzle/guzzle/src/Guzzle/Service/Resource/ResourceIteratorInterface.php
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
 3 | ERROR | 'resource' is a reserved keyword as of PHP version 7.0 and cannot be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------

FILE: /XXXXXX/wp-content/plugins/cloudflare/vendor/guzzle/guzzle/src/Guzzle/Service/Resource/ResourceIteratorFactoryInterface.php
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
 3 | ERROR | 'resource' is a reserved keyword as of PHP version 7.0 and cannot be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------

FILE: /XXXXXX/wp-content/plugins/cloudflare/vendor/guzzle/guzzle/src/Guzzle/Service/Resource/MapResourceIteratorFactory.php
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
 3 | ERROR | 'resource' is a reserved keyword as of PHP version 7.0 and cannot be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------

FILE: /XXXXXX/wp-content/plugins/cloudflare/vendor/guzzle/guzzle/src/Guzzle/Service/Resource/ResourceIterator.php
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
 3 | ERROR | 'resource' is a reserved keyword as of PHP version 7.0 and cannot be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
</code>
</pre>
<p>Please fix. Thank you.</p>
<br><br>
via WordPress.org Forums &raquo; [PHP Compatibility Checker] Support http://ift.tt/2gps7Vy<br>
February 27, 2017 at 07:43PM

**Comment by jrfnl** [comment]
This is not a false positive. `resource` is a reserved keyword and should not be used as part of a namespace.

The Cloudflare plugin uses a very outdated version of Guzzle (v3.9.3) which is not compatible with PHP 7.

**Comment by RedSandSD** [comment]
@octalmage 

BTW...nice job using IFTTT to auto-post issues from the WordPress forums here. I like it. :) More devs need to do that.

@jrfnl 

I understand where you're coming from. The plugin works fine in PHP 7+. We keep WP_DEBUG running 24/7 in logging mode on certain sites, and haven't had any error messages. Hence, the false positive.

Keep in mind that just because the code uses a certain library, doesn't mean it's executed. It may be...but keep that in mind. That was one of the issues with the plugin and a previous version of bbPress...it flagged code that the plugin literally never called.

**Comment by jrfnl** [comment]
@RedSandSD I'm glad to hear it all works fine.

For the PHPCompat plugin, there are potential "false positives" on two different levels.

1. The actual code being examined, In this case, the **code** is correctly being reported as incompatible.
2. The plugin itself. On a plugin level, I totally agree that code may not be called or cause problems in practice, but that is something for an experienced developer to evaluate on a per-plugin level.
In this case, the plugin is correctly flagged for such evaluation.

Once such evaluation would determine that the **plugin** does not call that code in as far as it's used by WordPress, it could be whitelisted by the PHPCompat plugin.

My previous comment just highlighted that for point 1, the report cannot be regarded as a false positive.

**Comment by RedSandSD** [comment]
@jrfnl 

From my perspective, if a plugin works correctly in PHP 7, without throwing any errors, then it is compatible, and reports to the contrary would be the definition of false positive.

> The actual code being examined, In this case, the code is correctly being reported as incompatible.

Don't forget that software is about users, not code. (And I'm saying this as an extremely experienced developer.)

> The plugin itself. On a plugin level, I totally agree that code may not be called or cause problems in practice, but that is something for an experienced developer to evaluate on a per-plugin level.

The thing is, experienced developers won't use this plugin to run compatibility tests. When experienced developers want to test PHP 7 compatibility, it's much more efficient, and accurate to use WP_DEBUG with logging, and run a gamut of real-world functionality on a PHP 7 system.

The main segment of WordPress users that are running your plugin are your "average Joe" WordPress site owners, that are not necessarily tech savvy, and definitely not experienced developers.

So, please be realistic about your users' needs. The people using it currently just want to know if it is safe to upgrade their site to PHP 7 or not. They just want a "Yes" or "No" when asking the question of, "Is this plugin PHP 7 compatibile?"

They don't have the experience or knowledge to make the determinations you're talking about.

Your initial target audience may have been experienced developers, or plugin developers, but that's not who's using it.

The only reason developers are evaluating it, is that major plugin developers are getting false positive reports from our users.

So please don't say it's not a false positive. It definitely is.

**Comment by jrfnl** [comment]
@RedSandSD You're addressing the wrong person. I'm not involved with the development of the plugin.

And while l don't agree with your arguments, I will gladly leave further discussion up to the actual plugin developers.

> They don't have the experience or knowledge to make the determinations you're talking about.

Correct, that's why I suggested an **_experienced developer involved with this plugin_** evaluate the plugin to determine whether or not it can safely be whitelisted.

**Comment by RedSandSD** [comment]
@jrfnl No worries! :)
