### ISSUE TITLE
clone [&#8230;] cannot be invoked as a function

### ISSUE THREAD

**Issue by octalmage** [wpengine/phpcompat#124]
&lsquo;clone&rsquo; [&hellip;] cannot be invoked as a function<br>
http://ift.tt/2ndig9P<br><p>Replies: 0</p>
<p>Hi,</p>
<p>I regularly get complains from my users that <a href="http://ift.tt/1yrzeVq" rel="nofollow">my plugin</a> is not compatible with PHP 7 since they see the error in the subject.</p>
<p>However, this is just incorrect. &lsquo;Clone&rsquo; can be used as a function and nothing wrong with that.</p>
<p>Is it planned to fix some day?</p>
<p>____________________________________________________________</p>
<p>FILE: /home/xxxxxxxx/public_html/xxxxxx/wp-content/plugins/weight-based-shipping-for-woocommerce/WC_Weight_Based_Shipping.php<br>
&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&ndash;<br>
FOUND 2 ERRORS AFFECTING 2 LINES<br>
&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&ndash;<br>
67 | ERROR | &lsquo;clone&rsquo; is a reserved keyword introduced in PHP version 5.0 and cannot be invoked as a function (T_CLONE)<br>
319 | ERROR | &lsquo;clone&rsquo; is a reserved keyword introduced in PHP version 5.0 and cannot be invoked as a function (T_CLONE)<br>
&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&ndash;</p>
<ul id="bbp-topic-revision-log-8898329" class="bbp-topic-revision-log">
<li id="bbp-topic-revision-log-8898329-item-8898354" class="bbp-topic-revision-log-item">This topic was modified 37 seconds ago by <a href="http://ift.tt/2nd7tN7" title="View Dan's profile">Dan</a>.</li>
</ul><br><br>
via WordPress.org Forums &raquo; [PHP Compatibility Checker] Support http://ift.tt/2gps7Vy<br>
March 10, 2017 at 05:58AM

**Comment by jrfnl** [comment]
This was fixed some three months ago. The PHPCompatibility library included with the plugin needs to be upgraded to take advantage of this.
