### ISSUE TITLE
Fatal error on activation

### ISSUE THREAD

**Issue by octalmage** [wpengine/phpcompat#125]
Fatal error on activation<br>
http://ift.tt/2mIZrM1<br><p>Replies: 0</p>
<p>Warning: require_once(__DIR__/vendor/autoload.php) [function.require-once]: failed to open stream: No such file or directory in /homepages/12/d439606240/htdocs/lfb/wp-content/plugins/php-compatibility-checker/wpengine-phpcompat.php on line 15</p>
<p>Fatal error: require_once() [function.require]: Failed opening required &lsquo;__DIR__/vendor/autoload.php&rsquo; (include_path=&rsquo;.:/usr/lib/php5.2&prime;) in /homepages/12/d439606240/htdocs/lfb/wp-content/plugins/php-compatibility-checker/wpengine-phpcompat.php on line 15</p>
<p>I&rsquo;ve had a look and can confirm that autoload.php does exist in the vendor subfolder.</p>
<p>Any ideas what&rsquo;s gone wrong?</p>
<br><br>
via WordPress.org Forums &raquo; [PHP Compatibility Checker] Support http://ift.tt/2gps7Vy<br>
March 15, 2017 at 07:32AM

**Comment by kumaxim** [comment]
Hi @octalmage 
Do you install the plugin from plugin directory or directly upload from github?

If you installed from github, then delete it and upload from plugin directory using the admin panel of your site. If this is not help for you then create in a root of site the file **info.php** with single line `<?php phpinfo(); ?>`. In a header you will see something like this 
> PHP 5.6.32
If you will see version below 5.3 then you using very outdated PHP version. The autoload.php works perfect start from 5.3 and above. You can see the "End of life" table of PHP versions in this table http://php.net/eol.php

**Comment by Pross** [comment]
__DIR__ was added in php 5.3 You are using 5.2 and as the previous person said 5.2 was EOL 6 years ago. Update your PHP version.
