### ISSUE TITLE
underscore.js tags being reported as warnings (ASP-like tags)

### ISSUE THREAD

**Issue by davilera** [wpengine/phpcompat#153]
Plugins that define underscore templates contain multiple warning messages like this:

```
FILE: /srv/www/wordpress-default/public_html/wp-content/plugins/nelio-content/admin/views/partials/social-message-editor/post-result.php
------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 2 LINES
------------------------------------------------------------------------------------------------------------------------------------------------------------
 29 | WARNING | Possible use of ASP style opening tags detected. ASP style opening tags have been removed in PHP 7.0. Found: <%= _.escape( thumbnail ) %...
 35 | WARNING | Possible use of ASP style opening tags detected. ASP style opening tags have been removed in PHP 7.0. Found: <%= titleFormatted %></div>
------------------------------------------------------------------------------------------------------------------------------------------------------------
```

Tags like `<%= ... %>` and `<% ... %>` are used by [underscore.js](http://underscorejs.org/#template) template system (a library included in WordPress core).

Some of our users were unsettled by all these warning reports. Is there something you can do in the report, so that it doesn't look like something is wrong?

**Comment by grappler** [comment]
Related to https://github.com/wpengine/phpcompat/issues/134

**Comment by jrfnl** [comment]
> Some of our users were unsettled by all these warning reports. Is there something you can do in the report, so that it doesn't look like something is wrong?

I'd strongly advise against this as there **_is_** something wrong.

While it may not be a PHP7 issue (ASP style tags were removed in PHP7), that type of code is dangerous when used in combination with PHP as any PHP installation running with `asp_tags` set to `on` will choke on your code and I've seen numerous reports in the WP forums of people having exactly that problem with plugins using underscores.

I've read in a couple of places (can't remember exactly where) that you can use `{{`mustache`}}` tags instead. That is definitely the better/safer option when combining underscores with PHP.

Looking at the underscores documentation, they actually mention it as well: http://underscorejs.org/#template

**Comment by davilera** [comment]
I thought I had to change a global setting to make this work (`_.templateSettings`), but `_.template` has as second parameter to customize my own templates. So I decided to follow @jrfnl tip and use mustache-like templates instead.

Here's the function I'm using now:

```
function _template( templ ) {
  return _.template( templ, {
    'evaluate': /\{\{#([\s\S]+?)\}\}/g,
    'interpolate': /\{\{[^#\{]([\s\S]+?)[^\}]\}\}/g,
    'escape': /\{\{\{([\s\S]+?)\}\}\}/g
  });
}
```

**Comment by jrfnl** [comment]
@davilera Glad it helped!
