### ISSUE TITLE
False positives for Amazon Web Services and WP Offload S3 Assets add-on

### ISSUE THREAD

**Issue by aaemnnosttv** [wpengine/phpcompat#155]
[Amazon Web Services](https://wordpress.org/plugins/amazon-web-services/)
False positives from Guzzle library used in AWS SDK.
[amazon-web-services-php7compat.txt](https://github.com/wpengine/phpcompat/files/1115570/amazon-web-services-php7compat.txt)

WP Offload S3 - Assets Addon
False positives from using `clone` keyword with parentheses - interpreted as function.
[amazon-s3-and-cloudfront-assets-php7compat.txt](https://github.com/wpengine/phpcompat/files/1115574/amazon-s3-and-cloudfront-assets-php7compat.txt)

These are all confirmed false positives as we have these covered by automated tests using PHP7 as part of our CI.

**Comment by grappler** [comment]
Do you have the code examples on where this is happening? The reason I ask is if we can work out why this is a false positive then it can be fixed at the source instead just putting plaster on it. https://github.com/wimg/PHPCompatibility/

Related #122

**Comment by aaemnnosttv** [comment]
The errors for the AWS plugin are all for the `resource` keyword being used, which is a namespace segment used by some classes in the Guzzle library, a dependency of the AWS SDK. Nothing we can do about that.

e.g. `amazon-web-services/vendor/aws/Guzzle/Service/Resource/ResourceIteratorClassFactory.php`

```php
namespace Guzzle\Service\Resource;
```

The Assets addon's errors come from another 3rd party library, [CssMin](http://code.google.com/p/cssmin/) 3.0.1 in `amazon-s3-and-cloudfront-assets/vendor/CssMin/`.

![image](https://user-images.githubusercontent.com/1621608/27753040-a206d102-5dec-11e7-8f9a-82abc708cbab.png)

Like `require` or `include`, `clone` can be used with parenthesis or without.

We could change this usage in the plugin but I think it would be better to update the parser if possible or at least whitelist the CssMin library (`CssMin/CssMin.php`) rather than our plugin as a whole.

Thoughts?

**Comment by grappler** [comment]
`resource` is a soft reserved keyword for PHP7. This means even though there will be no issue at the moment there could be a problem in the future.

For that reason I would say it does not make sense to make an exception.

As to the clone issue. This was fixed last December in https://github.com/wimg/PHPCompatibility/issues/284 but it has not been updated in 11 months. So the fix here should be to update PHPCompatibility and not add the plugin to the whitelist.

**Comment by octalmage** [comment]
This fix has been pulled in!
