### ISSUE TITLE
PHP 7.1

### ISSUE THREAD

**Issue by octalmage** [wpengine/phpcompat#156]
PHP 7.1<br>
http://ift.tt/2u3RqHl<br><p>Replies: 0</p>
<p>PHP 7.1 is available on Strato servers. When will this plugin support PHP 7.1?</p>
<br><br>
via WordPress.org Forums &raquo; [PHP Compatibility Checker] Support http://ift.tt/2gps7Vy<br>
July 10, 2017 at 04:32AM

**Comment by berlindave** [comment]
I also would appreciate the ability for testing 7.1.

**Comment by wormeyman** [comment]
It's supported now! You can close this.
