### ISSUE TITLE
Whitelist WooCommerce PDF Invoices & Packing Slips

### ISSUE THREAD

**Issue by Spreeuw** [wpengine/phpcompat#160]
[WooCommerce PDF Invoices & Packing Slips](https://wordpress.org/plugins/woocommerce-pdf-invoices-packing-slips/) gives 3 false positives in the scan, all three part of the dompdf library used by this plugin:
```
200 | ERROR | Using ‘break’ outside of a loop or switch structure is invalid and will throw a fatal error since PHP 7.0

197 | ERROR | Extension ‘cpdf’ is removed since PHP 5.1 – use pecl/pdflib instead.

36 | ERROR | Extension ‘cpdf’ is removed since PHP 5.1 – use pecl/pdflib instead.
```

1) This is not pretty code, but it is valid PHP ([source](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/216884f75277681a13cd9febad1a65048fee7ea6/vendor/dompdf/dompdf/src/FrameDecorator/Table.php#L198-L200)):
``` php
while ($frame = $frame->get_parent())
    if ($frame->is_table())
        break;
```
2) & 3. This is not the PHP5.1 cpdf extension but a class included in the plugin ([source](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/216884f75277681a13cd9febad1a65048fee7ea6/vendor/dompdf/dompdf/src/Adapter/CPDF.php#L197-L202)) ([bundled CPDF class](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/216884f75277681a13cd9febad1a65048fee7ea6/vendor/dompdf/dompdf/lib/Cpdf.php)):
``` php
$this->_pdf = new \Cpdf(
    $size,
    true,
    $dompdf->getOptions()->getFontCache(),
    $dompdf->getOptions()->getTempDir()
);
```

**Comment by grappler** [comment]
1. Is already reported in #138

2. I am not sure about this. Will let someone else reply.

**Comment by Spreeuw** [comment]
does that mean that you will wait until #138 is resolved rather than whitelisting this plugin?

**Comment by grappler** [comment]
@Spreeuw I don't make decisions around or have commit acces. Just try help out.

**Comment by octalmage** [comment]
Plugin added to the whitelist! Working on deploying 1.4.1.

**Comment by Spreeuw** [comment]
awesome, thanks @octalmage !

**Comment by Spreeuw** [comment]
@octalmage these cpdf false positives have started popping up again, could you re-add this to the whitelist? (see: https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/issues/65)
