### ISSUE TITLE
Allow specific plugin or theme to be scanned rather than all active.

### ISSUE THREAD

**Issue by toddlahman** [wpengine/phpcompat#257]
It would be ideal if a specific plugin/theme, or more than one, could be specifically selected for scanning to eliminate unnecessary scanning of plugins such as WooCommerce that has a large code base.

**Comment by Julix91** [comment]
Is duplicate of this one: https://github.com/wpengine/phpcompat/issues/216 and likely many others. It's an obvious good idea - wonder if it's technical reasons why it's not done? Maybe mention in FAQ

**Comment by mindctrl** [comment]
Thanks for bring this up! Let's continue the conversation on #67.
