### ISSUE TITLE
1.0.2 throwing JSON error on localhost

### ISSUE THREAD

**Issue by colinhowells** [wpengine/phpcompat#31]
Terrific plugin! Thanks for putting this together.

Wondering if anyone else has run into this when developing locally. Cropped up in 1.0.2:

<img width="595" alt="tinygrab screen shot 7-8-16 12 10 54 pm" src="https://cloud.githubusercontent.com/assets/2035314/16698904/ad05e9cc-4505-11e6-8966-51048ecb4ab9.png">

**Comment by octalmage** [comment]
I've seen it before with WP_DEBUG enabled. There's another report of it here: 

https://wordpress.org/support/topic/json-error-9?replies=5

The issue I was seeing was that errors were making it into the ajax call, so when the JavaScript tried to turn the JSON blob into an object it failed. Can you inspect the ajax call using the network tab in Chrome's dev tools to see what the response is? I haven't been able to replicate it since.

**Comment by colinhowells** [comment]
the response is 'started', lemme know if you want more info

**Comment by octalmage** [comment]
There should be a second ajax call with an action of "wpephpcompat_check_status", and this is the one that should return the json. Do you see the result of that one?

**Comment by colinhowells** [comment]
i don't have that one, i have multiple actions of 'heartbeat', with responses like
{"wp-auth-check":true,"server_time":1468020889}

**Comment by hello-jason** [comment]
I'm getting this same error.
![php-compatibility-checker-error](https://cloud.githubusercontent.com/assets/1406213/21547176/0006a1ca-cdaa-11e6-8a29-d7f7329cbd3a.png)

If it helps, this is the apache log at the same time:

`PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /home/jason/Sites/php/wpe-magazine-torqueold/wp-content/plugins/php-compatibility-checker/vendor/squizlabs/php_codesniffer/CodeSniffer/File.php on line 2446, referer: http://torqueold.dev/wp-admin/tools.php?page=php-compatibility-checker`

**Comment by colinhowells** [comment]
Same deal - JSON token error and fatal error when running locally, plugin version 1.3.2:
[16-Feb-2017 21:16:15 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 8388616 bytes) in /Applications/MAMP/htdocs/foo/wp-content/plugins/php-compatibility-checker/vendor/squizlabs/php_codesniffer/CodeSniffer/Tokenizers/PHP.php on line 984

**Comment by octalmage** [comment]
This should be resolved by 1.4.0 that has just been released (the JSON error).

**Comment by colinhowells** [comment]
Weirdly my copy kept upgrading itself to 1.3.2, so I thought that was the latest - downloaded 1.4.0 manually, and all is well - thank you!

**Comment by octalmage** [comment]
Fantastic! Glad to have this issue finally resolved. Let me know if you need anything else!
