### ISSUE TITLE
WordPress Notices breaks styling.

### ISSUE THREAD

**Issue by Pross** [wpengine/phpcompat#48]
![screen shot 2016-07-20 at 21 00 13](https://cloud.githubusercontent.com/assets/265860/17000977/0320ceb0-4ebd-11e6-9d29-b4d676380faa.png)

**Comment by octalmage** [comment]
I noticed that too! Wasn't sure if it was just me: 

![](https://cloudup.com/c2_Q84a5BMN+)

I'll see what I can do!

**Comment by Pross** [comment]
I have a PR for it ;)

**Comment by octalmage** [comment]
Ha perfect thanks!
