### ISSUE TITLE
Update PHP Compatibility Checker

### ISSUE THREAD

**Issue by edwarddekker** [wpengine/phpcompat#68]
Hi,

Today I have make a small investigation about your PHP Compatibility Checker. And came by the results that your PHP Sniffer is outdated. Please update your version at https://github.com/wimg/PHPCompatibility/ and pull this update to your WordPress Plug-in installation.

Best of regards,
Edward Dekker

**Comment by octalmage** [comment]
Hi @edwarddekker! 

Thanks for the issue, we update the library at least every 2 weeks. A new version will be out soon. 

Please let us know if you need anything else!
