### ISSUE TITLE
Handle E_DEPRICATED warnings not as Errors

### ISSUE THREAD

**Issue by Taylor4484** [wpengine/phpcompat#73]
We're counting E_DEPRECATED warnings as "errors."   In particular, deprecated PHP4-style constructs, which (from my small test) appears to be extremely common, even in PHP7-compatible, high-quality plugins like the WordPress API and WPTouch.

**Comment by Taylor4484** [comment]
Reported by @asmartbear

**Comment by Taylor4484** [comment]
TODO: Open issue with PHPCOMPAT library, see how wim responds, potentially fork library and fix it. Option two have the plugin just ignore that for now.

**Comment by Taylor4484** [comment]
Great news, there is a pull request against PHPCOMPAT to fix this issue: 
https://github.com/wimg/PHPCompatibility/pull/286

**Comment by wimg** [comment]
This issue was merged upstream ;-)
