### ISSUE TITLE
Add TablePress to whitelist

### ISSUE THREAD

**Issue by TobiasBg** [wpengine/phpcompat#78]
Hi,

I've been getting numerous [support tickets](https://wordpress.org/support/plugin/tablepress/) in the wordpress.org forums recently, all claiming that the TablePress plugin is not compatible with PHP 7.0.

While TablePress does indeed contain functions calls/dynamic libraries that are deprecated or removed in PHP 7.0, this is taken care of through corresponding checks during runtime.
See e.g. https://wordpress.org/support/topic/tablepress-php-70-compatibility/ and https://wordpress.org/support/topic/php7-compatibility-42/#post-8325041

I'd therefore like to ask for TablePress to be added to your whitelist. Thanks!

Best wishes,
Tobias

**Comment by octalmage** [comment]
Hi Tobias, 

I'll take care of it this morning! Stay tuned.

**Comment by octalmage** [comment]
This has been resolved by 1.2.4. 

Please let us know if you need anything else!
