### ISSUE TITLE
Download-Monitor is a false positive

### ISSUE THREAD

**Issue by Texiwill** [wpengine/phpcompat#84]
The Download-Monitor plugin presents a false positive when it is scanned for PHP 7.0 compatibility. The issue is set_magic_quotes_runtime, which is deprecated. Download-Monitor protects against this by doing the following:
```
                if ( function_exists( 'get_magic_quotes_runtime' ) && get_magic_quotes_runtime() ) {
                        @set_magic_quotes_runtime( 0 );
                }
```

This looks like the proper protection. 

Thoughts?

**Comment by octalmage** [comment]
Looks fine to me! I'll get it whitelisted. Thanks!
