### ISSUE TITLE
Update PHPCS to version 2.7.1

### ISSUE THREAD

**Issue by grappler** [wpengine/phpcompat#96]
Is there a reason why PHPCS `2.6.1` is being used? WPCS is using `2.7` and is thinking about updating to `2.7.1`.

The reason I realized that is that I was creating a plugin of my own and was getting an error that a sniff was missing but could not understand why before I realized PHPcompat was active on the site too and I was not loading my autoloader.

**Comment by octalmage** [comment]
No reason other than we just needed to update!
